### ISSUE TITLE
Some Files are Missing or Corrupted

### ISSUE THREAD

**Issue by Person2099** [fan-zhang-sv/COVID-Panel-SwiftUI#1]
When Cloning this repo I have immediately encountered an issue. It seems a lot of files are missing or corrupted, although I am not sure if this is an issue on my end or an issue with the repo. Advice would be very helpful, I have tried cloning to Xcode Version's 12.5.1 and 13.0 Beta 5. Screenshots are provided below. 

@fan-zhang-sv I would also appreciate if you provided me with the api's for `CovidDataGrabber.swift` and `MapDotUpdater.swift`

**Screenshots:**
<img width="272" alt="Screen Shot 2021-09-03 at 5 23 55 pm" src="https://user-images.githubusercontent.com/51016337/131967472-2eaf37e2-130a-410f-a3d8-b81ae946ab04.png">
<img width="272" alt="Screen Shot 2021-09-03 at 5 24 04 pm" src="https://user-images.githubusercontent.com/51016337/131967480-45279dd1-adcb-4d17-ab39-064ba8b805ef.png">
<img width="722" alt="Screen Shot 2021-09-03 at 5 24 36 pm" src="https://user-images.githubusercontent.com/51016337/131967485-17291b46-9f53-41bb-95f9-12bfe4a203aa.png">

**Comment by Person2099** [comment]
I noticed the files I listed are included in the gitignore. Can you elaborate on what they contain.

**Comment by fan-zhang-sv** [comment]
Sry i just saw this ticket. Unfortunately, the API already expired. But if you'd like a quick demo of this app, you can switch to the demo branch, in which the app would show using dummy data. Thanks
